### ISSUE TITLE
You've committed your AWS credentials

### ISSUE THREAD

**Issue by adamlwgriffiths** [sdutta9/Amazon_Product_Rating_Analysis#1]
Unless you want a massive bill, I suggest you remove this configuration file and de-authenticate these credentials.

https://github.com/sdutta9/Amazon_Product_Rating_Analysis/blob/master/amazon.cfg

For all intents and purposes, your account is now compromised.

https://securosis.com/blog/my-500-cloud-security-screwup

**Comment by sdutta9** [comment]
Thanks Adam. I have removed the file.

**Comment by adamlwgriffiths** [comment]
Just to be clear, those credentials are in the git history and can be easily retrieved by a bot. You must treat those credentials as compromised and ensure they are invalidated on the AWS console.

**Comment by adamlwgriffiths** [comment]
For example
https://github.com/sdutta9/Amazon_Product_Rating_Analysis/commit/26b53d923469abce20ac68f775998accbfdd00d0

Regardless, there is a chance that while the file was up, a bot managed to get the details. You must treat these credentials as compromised, committing over the top of them will not suffice.

**Comment by hparik11** [comment]
I have inactivated these details on AWS already. So these credentials are of no use.
